# Generated by Django 3.0.1 on 2020-01-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200104_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Last activity date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
