# Generated by Django 3.0.1 on 2020-01-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200104_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
