# Generated by Django 3.0.1 on 2020-01-06 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200104_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='front_key',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='frontend key'),
        ),
    ]
