# Generated by Django 3.0.1 on 2020-01-07 00:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_pending_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='front_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='frontend key'),
        ),
    ]
