# Generated by Django 3.0.1 on 2020-01-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitation_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='link',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='link',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
